// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoWbJP7nAYb3d192eYt0UR0l24c6DIpjY',
    appId: '1:8578502738:web:c86d0468548464fadb0f8b',
    messagingSenderId: '8578502738',
    projectId: 'hyrule-compedium-login',
    authDomain: 'hyrule-compedium-login.firebaseapp.com',
    storageBucket: 'hyrule-compedium-login.appspot.com',
    measurementId: 'G-NZW4QHNPZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVB4j_j1cDTJbbTEDYpgbSfylr1xOaTwo',
    appId: '1:8578502738:android:805685a54dc8acf3db0f8b',
    messagingSenderId: '8578502738',
    projectId: 'hyrule-compedium-login',
    storageBucket: 'hyrule-compedium-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbP013bonkS9jdDCKiSVcQAz6Qr2P_G6A',
    appId: '1:8578502738:ios:2433095c908bd93cdb0f8b',
    messagingSenderId: '8578502738',
    projectId: 'hyrule-compedium-login',
    storageBucket: 'hyrule-compedium-login.appspot.com',
    iosBundleId: 'com.example.practiceListView',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbP013bonkS9jdDCKiSVcQAz6Qr2P_G6A',
    appId: '1:8578502738:ios:2433095c908bd93cdb0f8b',
    messagingSenderId: '8578502738',
    projectId: 'hyrule-compedium-login',
    storageBucket: 'hyrule-compedium-login.appspot.com',
    iosBundleId: 'com.example.practiceListView',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoWbJP7nAYb3d192eYt0UR0l24c6DIpjY',
    appId: '1:8578502738:web:c4997c0396f1332bdb0f8b',
    messagingSenderId: '8578502738',
    projectId: 'hyrule-compedium-login',
    authDomain: 'hyrule-compedium-login.firebaseapp.com',
    storageBucket: 'hyrule-compedium-login.appspot.com',
    measurementId: 'G-KH577WQ12E',
  );
}
